### ISSUE TITLE
Bug report on getAction function of Tf2t class

### ISSUE THREAD

**Issue by Shoei256** [cristal-smac/ipd#5]
According to the definition of Tf2t, Tf2t strategy will defect only when the opponent defected in the previous two moves.
In your implementation of Tf2t, it will defect when the opponent defected in the previous move, so
I think the following program needs to be modified. We present the modified version as “After fix”.

**Now**
https://github.com/cristal-smac/ipd/blob/e6862a8edc66a937394c6272eb397b72d5109c06/src/strategies.py#L60-L67

**After fix**
```
    def getAction(self, tick):
        if tick == 0 or tick == 1:
            return "C"
        else:
            if self.hisPast[-1] == "D" and self.hisPast[-2]=="D": #here
                return "D"
            else:
                return "C"
```

**Comment by pmathieufr** [comment]
Thanks a lot.
Committed
Do not hesitate to contact me direclty.
